### ISSUE TITLE
Possible bug in get_symbol_by_cmeta_id

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#156]
Again using my very basic model:

    <component name="env_ode">
        
        <variable name="time" public_interface="in" units="ms"/>
        <variable cmeta:id="sv11" initial_value="2" name="sv1" units="mV"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
                <eq/>
                <apply>
                    <diff/>
                    <bvar>
                        <ci>time</ci>
                    </bvar>
                    <ci>sv1</ci>
                </apply>
                <cn cellml:units="mV_per_ms">1</cn>
            </apply>
        </math>
    </component>

no node is every created for the variable sv1 and so get_symbol_by_cmeta_id('sv11')  does not find the variable.

The model is so simple it does not ever occur as lhs of anything but it would be the variable that was the output of simulating this toy model.

Bug or not ??

**Comment by jonc125** [comment]
This is perhaps similar to #121, but with the state rather than free variable?

Although I think here the proper (immediate) fix is to change `get_symbol_by_cmeta_id` to use the `VariableDummy` objects rather than the graph: `for v in self._name_to_symbol.values()` etc.

Which means actually we should probably implement `get_free_variable_symbol` in the same way.

Do we also want to add free variable and state variable nodes to the graph if they aren't connected to anything? Depends whether it's useful to have disconnected nodes in the graph really. Arguably possibly yes, since a user might want to find all equations that they depend on, and getting the empty set is then a valid result!

**Comment by MichaelClerx** [comment]
> This is perhaps similar to #121, but with the state rather than free variable?
> 
> Although I think here the proper (immediate) fix is to change `get_symbol_by_cmeta_id` to use the `VariableDummy` objects rather than the graph: `for v in self._name_to_symbol.values()` etc.
> 
> Which means actually we should probably implement `get_free_variable_symbol` in the same way.

Not quite I'm afraid! The cmeta id is a property of a `VariableDummy`, but the variable type (e.g. free) is a property of the equations, as represented by the graph. That's pretty much what #149 is about

**Comment by skeating** [comment]
Nearly all the get functions on a model use the graph nodes to find things - I think it would be more than two functions that changed :-) I'll fix the bug by adding the state variable to graph and add another issue to change the functions - which I will do when I'm finished all the tests !

**Comment by jonc125** [comment]
> The cmeta id is a property of a `VariableDummy`, but the variable type (e.g. free) is a property of the equations, as represented by the graph. That's pretty much what #149 is about

True, but it's a property that's also stored on the `VariableDummy`. I guess you need to have instantiated the graph to guarantee it's calculated though, so probably best accessed from the graph, yes.
