### ISSUE TITLE
Retreive data from variables not graph

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#159]
Since many get functions parse the graph and its nodes to get information which should be in the underlying internal structure - change the methods to use the internal structure.
See #156

**Comment by skeating** [comment]
When looking into this I realised that the free and state variables are only tagged as such within the graph.  So options
1) leave all functions to query graph (so don't do this issue !)
2) change so free/state variables get tagged in the VariableDummy list on model and continue with issue

**Comment by jonc125** [comment]
I seem to recall discussing this with @MichaelClerx on another issue; can't recall which offhand. We thought that the classification of variables as state/free/parameter/computed was really a property of the system of equations, rather than the variables themselves, so only made sense when you had a graph. Hence it probably makes sense to keep it there, rather than having to remember to invalidate it elsewhere when the equations are changed.

This is in contrast to properties such as name & units, which are definitely associated with the variable itself.

**Comment by MichaelClerx** [comment]
I'm not sure what to do about this!

The big picture issue is this:

1. Cellmlmanip reads cellml, lets you modify it, lets cg write code
2. It does so by tying together a bunch of other tools, including sympy (to represent equations), pint (to do units and unit conversion), and networkx (to resolve dependencies, so maybe this is overkill?)

The value of cellmlmanip would come exclusively from _hiding these components from the user_. Otherwise they can just hack stuff together themselves.

I don't think the current design achieves this goal and I'm not sure how to make it so that it can do this (because users get pint unit objects, use sympy to change equations, and we pass them the graph occasionally too).

I'm not sure we _need_ networkx for example, because resolving dependencies is a very easy problem, and just doing this ourselves would make it easier for the user (one less dependency to install and learn about).

In addition the current API is designed for CellML parsing, which is not the goal of this project. So there are lots of public methods, properties, and arguments which are for internal parsing use.

So my idea of how to tackle this project would be to have a very minimal public API that we iteratively update when needed. But as @jonc125 has pointed out we don't know what that API should be yet and so we're just hacking everything together until we know what the requirements are and then we'll tidy it up once we know which features we want?

Personally I find it very difficult to work this way or and I keep going round in circles trying to tidy up the code so that I can get some overview of what it all means, and then stopping again because it's not the current goal.

What I want to say with all of that is that I how no idea of how to answer design questions like this because the style we're using for this project is so far away from my own that none of my intuition or experience are any help

**Comment by skeating** [comment]
So looking at Model get functions:
The following use the graph:
- get_derivative_symbol
- get_equations_for
- get_free_variable_symbol
- get_state_symbol

The following should use internal model structure:
- get_symbol_by_name

The following should use internal model structure (IMHO) but currently use graph:
- get_symbol_by_cmeta_id

Note other get functions either take a symbol argument to get data or use the rdf graph so are not relevant here.

So my conclusion would be that 'get_symbol_by_cmeta_id' should change BUT that falls over (in a very convoluted way) because the VariableDummy type is not set on the model's internal structure. See 159-get_data_from_equations branch. 

This will taking digging(time) to work out. Do I pursue or put on hold for now ?

**Comment by jonc125** [comment]
I agree with your conclusion about what should change. That it breaks is bizarre! Whenever a `VariableDummy` is created and added to `_name_to_symbol` it has to have a `cmeta_id` property - it's set in the constructor. I wouldn't necessarily prioritise trying to figure it out now though.

Incidentally, you could do `for var in self._name_to_symbol.values():` to simplify the loop a bit.

**Comment by skeating** [comment]
Ah ! I do need it when doing conversion. I need to move the cmeta_id from one variable to another - and I may not have the full graph. I definitely need to be able to grab it from _name_to_symbol.
