### ISSUE TITLE
General review process

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#164]
Hi Guys.
can we discuss the general review process as I'm starting to find it a bit frustrating?
Also I just proposed a PR template see #163

**Comment by jonc125** [comment]
Responding to some comments on #163, firstly from @MauriceHendrix :

>     * I get most of my PRs immediately shot down, even (or especially) after they've been discussed on slack. I do recognize we probably need to provide better info (hence the pull request template), but I would really appreciate a more supportive environment!

Sorry for where I've been guilty of this! I suspect it's because I've not had time to be very familiar with the code base, so sometimes get surprised by things coming up that I thought should already be done by the existing code.

>     * I see a lot of tinny comments like typos, style/syntax comments leading to a change request that then ages to get re-approved. What a colossal waste of everybody's time!
>       In my view if you agree with the concept another round of reviews should not be necessary, so this should lead to an approve, but with comments. If we can't trust each other to do the little fixes needed we've got bigger problems in my opinion.
>       By the way typos can be easily corrected via the web interface. I don't know what people think but I would prefer reviewers to just make the change. (For the record I do agree typos are important).

I agree to make reviews an 'approve' if it's just trivial changes. I think I generally do this, but may occasionally forget!

At one point GitHub trialled a feature where you could suggest edits as part of a PR review, but this doesn't appear to be available (at least not for me) at present. The downside of editing the file online is it takes you to another page, you've got to find the line, make & save the change, then find your way back to your review - it interrupts the flow dramatically.

There's also the issue of timeliness of reviews. There's a challenge here because at least for @skeating & myself this project is at most half our workload (less in theory for me) so it can be days before we get to things. Hopefully as the core API stabilises PR reviews will stop being such significant blockers on progress...

>     * When reviewing a PR that fixes something in pre-existing code code can we please try to keep it focused on that change? Of course is there is a genuinely better way of doing things sure, but I've been dragged into justifying and explaining code that was there already or refactoring substantial bits just to get a tiny fix accepted. I know I should probably be more assertive in saying 'not for this PR'.

Very much agree with this!

@MichaelClerx suggested this general approach:
1. Create an issue stating the problem and proposed solution, or introducing the feature you want to add.
2. Discuss the proposal on the issue page. For really big things maybe sketch a solution, and agree on method and class names. Discuss how these changes will affect other parts of the code.
3. Once a vague idea / direction is accepted, code up a solution and add a PR

I do think this is good in general, provided we don't stick to it too slavishly, particularly for small changes. Sometimes a discussion on Slack can be a good alternative or precursor to step 1.

@MichaelClerx mentioned the [https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md](pints approach). That's a very long document! I don't think we need to be that formal (yet) - we're still a very small team with a rapidly evolving codebase. That kind of structure is better for a more mature code with external/new contributors getting involved, I think. Not that it's bad, just intimidating!

**Comment by MichaelClerx** [comment]
> I  do think this is good in general, provided we don't stick to it too slavishly, particularly for small changes. Sometimes a discussion on Slack can be a good alternative or precursor to step 1.

Fine with that, but I do prefer issues to slack as it stops discussions from being spread over several places!

> @MichaelClerx mentioned the [https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md](pints approach). That's a very long document! I don't think we need to be that formal (yet) - we're still a very small team with a rapidly evolving codebase. That kind of structure is better for a more mature code with external/new contributors getting involved, I think. Not that it's bad, just intimidating!

Agreed!

**Comment by MauriceHendrix** [comment]
> > I  do think this is good in general, provided we don't stick to it too slavishly, particularly for small changes. Sometimes a discussion on Slack can be a good alternative or precursor to step 1.
> 
> Fine with that, but I do prefer issues to slack as it stops discussions from being spread over several places!
> 
> > @MichaelClerx mentioned the [https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md](pints approach). That's a very long document! I don't think we need to be that formal (yet) - we're still a very small team with a rapidly evolving codebase. That kind of structure is better for a more mature code with external/new contributors getting involved, I think. Not that it's bad, just intimidating!
> 
> Agreed!

In my experience trying to get people in my other team to use version control at all, the easier and smaller guidelines are the more chance people will stick by them. While the long document is well written and it all makes sense, it's a) daunting for newcomers and b) hard to remember to check everything

**Comment by jonc125** [comment]
> > I  do think this is good in general, provided we don't stick to it too slavishly, particularly for small changes. Sometimes a discussion on Slack can be a good alternative or precursor to step 1.
> 
> Fine with that, but I do prefer issues to slack as it stops discussions from being spread over several places!

I agree with that. Perhaps the guideline should be a pre-discussion on Slack is fine, but copy-paste onto GitHub when you then create the issue/PR, so we have a record?

**Comment by MauriceHendrix** [comment]
> > > I  do think this is good in general, provided we don't stick to it too slavishly, particularly for small changes. Sometimes a discussion on Slack can be a good alternative or precursor to step 1.
> > 
> > 
> > Fine with that, but I do prefer issues to slack as it stops discussions from being spread over several places!
> 
> I agree with that. Perhaps the guideline should be a pre-discussion on Slack is fine, but copy-paste onto GitHub when you then create the issue/PR, so we have a record?

sounds fine.

**Comment by MichaelClerx** [comment]
This PR template is quite massive! @MauriceHendrix could you adapt it a bit for this project? For example
- The bit that says this needs change to docs --> Just update the docs then!
- My code follows the code style of this project --> We have flake8 for that?
- I have read the CONTRIBUTING document. --> It's only us, so this can go?
- I have added tests to cover my changes. --> This is automatically checked
= All new and existing tests passed. --> Same
