### ISSUE TITLE
Add method to obtain unit name

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#222]
Given a `pint.unit` we'd like to know its name. This used to be possible with `str(unit)` but that now adds a prefix we need to strip

**Comment by MichaelClerx** [comment]
A use case is showing what unit a variable is in.
This will have to be something like

```
v = model.get_symbol_by_ontology_term(oxmeta, 'membrane_voltage')
print(model.units.format(v.units))
```

Thoughts @jonc125 @MauriceHendrix ?

**Comment by MauriceHendrix** [comment]
it would be nice so tht my generated code could output for example
`const double var_chaste_interface__cell__stim_period = 1000.0; // millisecond`
instead of hwat I get now:
`const double var_chaste_interface__cell__stim_period = 1000.0; // s1_millisecond`

functionally it makes no difference of course but people might wonder where that prefix comes from
