### ISSUE TITLE
celsius is not defined in the unit registry

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/cellmlmanip#339]
Tried to load up a model that OpenCOR is happy with, but cellmlmanip is complaining about it having units of celsius in there.
https://models.physiomeproject.org/workspace/5fd/@@file/e1c2a49185ddc44b0b55b1902dd08340a41e8f0b/  

Then tried to put in the unit definition in OpenCOR in terms of defining it in Kelvin with an offset, but then OpenCOR won't let me save that because celsius is already defined there!

I see they have been taken out of CellML2.0 but seem to appear in CellML 1.0 https://www.cellml.org/specifications/cellml_1.0 so we should probably include the definition to be nice?

**Comment by MauriceHendrix** [comment]
Interesting. That message is a pints error (the wording comming from cellmlmanip is different). It's odd because we specifically describe celcius as a base unit. I'll investigate further.

**Comment by MauriceHendrix** [comment]
right @mirams @jonc125 so I think cellmlmanip is right here in that celcius is not in the cellml spec: [units in cellml spec](https://www.cellml.org/specifications/cellml_1.1/#sec_units) so the model file should specify the unit. The cellml file should ave a unit definition for celsius
```
<units name="celsius" base_units="yes" />
```

Having said that adding this introduces a new error. While open-cor doesn't mind, cellmlmanip complaints about the re-definition of a known base-unit.
The reason for this behaviour seems to be:

- in unitys.py we do the following for setting up a unit registry, this looks at cellml_units.txt for the spec units, which (correctly) excludes celsius. This is used when parsing the components which is why that throws the error that it doesn't know cesius
```
self._registry = pint.UnitRegistry(os.path.join(os.path.dirname(__file__), 'data', 'cellml_units.txt'))
```
- When processing the unit definitions however the `add_unit` method (in units.pt) checks the units being specified aren't already in _known_units to prevent duplicates. The `__init__` method of the unit store adds the base units to this and this bit includes cellml.

So we need to decide what we want to do and whether we really want to be that strict about it.

**Comment by mirams** [comment]
`celsius` is in that table of the CellML1.0/1.1 spec as "units that any CellML processing application is expected to recognise", which I assumed means it doesn't need defining in a given CellML file?

**Comment by MauriceHendrix** [comment]
o yes you're right it is, I miss-read in that case it's an asy fix!
