### ISSUE TITLE
Should we validate the file, or at least check if there's stuff in there we don't use

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#45]
Two related issues:

1. CellML 1.0 allows lots of extra content which shouldn't have meaning. Should we do anything about this?

2. The current implementation searches for things it expects. As a result it won't notice if there are things in the file that we're not explicitly looking for. Should we do anything about this?

**Comment by MichaelClerx** [comment]
@tamuri points out there's also:

3. Things we know we're ignoring (e.g. reactions)

**Comment by mirams** [comment]
If it is easy enough to check, I think it would be nice to throw an error for anything that isn't going to be handled nicely (e.g. Reactions) to avoid silent nasty failures if people try and use CellML1.0 features we don't support.

But if it is going to take a while to do, then in the interests of agility let's just make sure it works for everything in https://github.com/Chaste/cellml/tree/master/cellml

**Comment by jonc125** [comment]
No models use reactions and nothing supports them, so probably OK to be quiet about that. Non-CellML content is also explicitly allowed (in the spec) to be ignored by implementations and must not affect the mathematical interpretation of the model, so we're fine to ignore that too.

Warning about things like component-level units, which are in the CellML spec but we're ignoring (because they go away in later version) would be nice though. Not a top priority.

**Comment by MichaelClerx** [comment]
Closing for now. We can add a more structured set of tickets for this at a later stage
