### ISSUE TITLE
Where exactly does the "manip" bit in "cellmlmanip" come in?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#47]
It seems to me the current weblab / fc code makes users change the cellml code, so all "manip" in this sense would happen before parsing, is that right @jonc125 ?

So the "manip" bit would be things like, determine the 2nd order derivatives or simplify the equations or something, but not actually manipulate the cellml model structure (which we throw out when parsing)?

**Comment by jonc125** [comment]
No, the manipulations specified by the protocol are entirely at the semantic level of 'system of equations', no knowledge of CellML structure, and reference variables entirely via ontology terms. So cellmlmanip needs to be able to apply these modifications *after* parsing.

It only looks like it's before in pycml because its equation model is tightly tied to the XML structure.

**Comment by MichaelClerx** [comment]
Ok that's good. @tamuri does the Dummy system ensure that all labelled variables stick around for manipulation?
