### ISSUE TITLE
Adding unit conversion for  code generation

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#77]
Code generation needs to be able to convert units. Currently Maurice is doing

factor = model.units.get_conversion_factor(1 * current_units, desired_units)
eq = sp.relational.Equality(eq.lhs, factor * eq.rhs)

which works so long as lhs isnt used elsewhere.

This issue will overlap with parts of other issues e.g. #8, #21 but adding it here to be clear what I'm working on.

**Comment by jonc125** [comment]
Principles:
- cellmlmanip should provide a general approach to adding conversions at model/world interfaces (whether the 'world' is Chaste or a WL protocol)
- It will do so by adding a new variable in the units desired by the world (if these are different from the model's units), transferring RDF annotations to the new variable (by just moving the `cmeta:id` in XML terms), and adding/changing equations as necessary so the new variable behaves appropriately.
- Inputs and outputs are with reference to the model. So an 'input' is when the world wants to change a model variable; 'output' is when the world wants to read a model variable.
- Only state variables, constants, or the free variable can be inputs. A variable calculated by an expression cannot (unless the expression is just a number, as this is really a constant).
- Any variable can be an output.

Some useful bits of pycml code to look at:
- Specific to Web Lab (all code in `protocol.py` falls in this category):
    - `protocol.py:_split_all_odes` adjusts all ODEs to account for time being units-converted. It assigns each RHS to a new variable in the original model units, and creates a new derivative in the new units to which this is assigned.
    - `protocol.py:specify_as_output` deals with creating new variables when needed for outputs
    - `protocol.py:process_input_declarations` deals with inputs
    - Actually adding the units conversions is done at a later processing stage in the `finalize` method by `_add_units_conversions`. With the simpler maths representation I'm hopeful we can do this more easily now!
- Specific to Chaste code generation (the `InterfaceGenerator` class is just used for Chaste):
    - `processors.py:_split_ode` does a similar transformation to `_split_all_odes` for handling a state variable being declared as an input (i.e. Chaste wishes to be able to adjust its value)
    - `processors.py:_transform_derivatives_on_rhs` will update all references to things like dV/dt on the RHS of any equation in the model to refer to the new variables created above, to ensure they're seeing the units they expect
    - Hopefully we can design `cellmlmanip` to avoid this duplication of logic...
- Code in the `processors.py:ModelModifier` class is common to both. Mainly this manages the fact that pycml keeps the notion of components, so adding/removing variables is complicated! It tries to update connections as required and ensure pycml's internal state is consistent.
- `processors.py:UnitsConverter` is a high-level interface for adding units conversions. Again most of the complexity is due to the maths representation. But there's also the logic for 'special' conversions that can convert between dimensions (notably used for currents).

**Comment by jonc125** [comment]
@MichaelClerx @MauriceHendrix @skeating let me know if you have any questions on the above :)

**Comment by MichaelClerx** [comment]
> Only state variables, constants, or the free variable can be inputs. A variable calculated by an expression cannot (unless the expression is just a number, as this is really a constant).

So x = 1, y = x means y can't be an input, right? So only literal constants?

**Comment by jonc125** [comment]
> > Only state variables, constants, or the free variable can be inputs. A variable calculated by an expression cannot (unless the expression is just a number, as this is really a constant).
> 
> So x = 1, y = x means y can't be an input, right? So only literal constants?

That's correct, yes.

**Comment by MichaelClerx** [comment]
Let's spell out the "adding/changing equations as necessary" bit for inputs:

## Literal constant
Example: Set `current` as an input, in `nA`
```
x = 1 [pA]
  in [pA]
  oxmeta: current
y = 1 / x
  in [1/pA]
```
would become
```
input_current = 1 [pA] * 1e-3 [nA/pA]
  in [nA]
  oxmeta: current
x = input_current * 1e3 [pA/nA]
  in [pA]
y = 1 / x
  in [1/pA]
```
## State variable
Example 1: Set `voltage` as an input in `V`
```
dot(V) = -1 / i_ion
  in [mV]
  oxmeta: voltage
i_na = g * (V - E)
  in [pA]
...
```
could become
```
dot(input_V) = -1 / i_ion * 1e-3 [V/mV]
  in [V]
  oxmeta: voltage
V = input_V * 1e3 [mV/V]
  in [mV]
i_na = g * (V - E)
  in [pA]
```
but what if we also use dV/dt somewhere?
```
dot(input_V) =  input_derivative_V * 1e-3 [V/mV]
  in [V]
  oxmeta: voltage
input_derivative_V =  -1 / i_ion
  in [mV/ms]
V = input_V * 1e3 [mV/V]
  in [mV]
i_na = g * (V - E)
  in [pA]
some_variable = 3 * input_derivative_V
```
In this case we'd have to update the equation for `some_variable`, changing it from `dV/dt` (which is no longer available since V has been demoted to an ordinary variable) to `input_derivative_V`
## Free variable

**Comment by jonc125** [comment]
Literal would become:
```
input_current = 1e-3 [nA]
```
but otherwise as you have it.

The state variable example would be as you've written it, although I'd call `input_derivative_V` `original_dV_dt` instead!

For the free variable, you alter every single ODE in a similar way to the state variable example. So something like
```
input_t = 0 [s] (initial value)
  in [s]
  oxmeta:time
t = input_t * 1000 [ms/s]
  in [ms]
orig_dV_dt_rhs =  -1 / i_ion
  in [mV/ms]
new_dV_dt_rhs = orig_dV_dt_rhs * 1000 [ms/s]
  in [mV/s]
dot(V) = new_dV_dt_rhs
  in [mV]
  oxmeta:voltage
```
and all references to `dV/dt` get changed to use `orig_dV_dt_rhs` instead.

**Comment by MichaelClerx** [comment]
Thanks! Have updated accordingly.
Why would the `input_current` RHS be evaluated/simplified? What if it's more complex, e.g. `x = (1 [pA] + 2 [pA])`, would that lead to `input_current = 3e-3 [nA]` ?

**Comment by jonc125** [comment]
But that `x` couldn't be an input, as it's a complex computed variable.

**Comment by MichaelClerx** [comment]
Oh ok so an input needs to be a number!
...
Turns out I've been thinking of expressions like `1+1` as "literals", since they don't refernce any variable. But that's not the definition of a literal at all :sweat_smile:

**Comment by MauriceHendrix** [comment]
All this is exactly how I understood it as well. 

Moving the `cmeta:id` is important as otherwise I can't recognize the relevant variables. 
I haven't looked at the code in great detail but the new variables like `original_dV_dt` might need some metadata and maybe a made up `cmeta:id` as I think various other parts of the code expect variables to have this. 

What I'm wondering about is the units: will you put the ones asked for? And what if those are not in the model? It would be very nice if we didn't have to add those units to the model first (like is the case now). 
Also what if I ask for say `ms` and the model already has `millisecond`. will we just have some bits in `ms` and some in `millisecond`? That's fine by me but we should make sure we warn users NOT to do `model. model.units.summarise_units(term1) == model. model.units.summarise_units(term2)

Finally the big question: who is going to implement all this :)

**Comment by jonc125** [comment]
The new variables shouldn't necessarily need RDF. Adding a `cmeta:id` should I think only be done at the point of need. So if code decides it wants to add an annotation for a variable, the id should be created at that point (so `cellmlmanip` will need a `Model` method to add an annotation, which can handle this, for instance).

I think units should be added transparently as needed too. To some degree I believe `pint` can do this for us, as it 'creates' unit definition objects as needed from expressions? The possibly complex bit is as you say if you want a 'nice' name for the units, which only matters either when referring to them by name (which I don't think we should do after the parsing - much easier to refer to actual objects) or when reporting to users. In my opinion, given a units definition, `summarise_units` should check if it matches one defined in the model (or protocol, depending on context) and use that name if so. Otherwise (for derived units) it could make one up?

**Comment by MauriceHendrix** [comment]
I think not having dummy metadata it may break  `get_derivative_symbols` and `get_state_symbols`
because of the:
`return sorted(derivative_symbols, key=lambda state_var: self.get_meta_dummy(state_var.args[0]).order_added)`
and
`return sorted(state_symbols, key=lambda state_var: self.get_meta_dummy(state_var).order_added)`



Also I was thinking:

I cannot do this at the moment
`f = model.units.get_conversion_factor(model.units.ureg.ms, from_unit=model.units.summarise_units(self._model.get_free_variable_symbol())`

because the model may not have ms yet or even just call it millisecond. 
Right now I have to do:
```try:
    model.units.add_custom_unit('ms', [{'prefix': 'milli', 'units': 'second'}])
except AssertionError:
    pass  # Unit already exists, but that is not a problem
f = model.units.get_conversion_factor(model.units.ureg.ms, from_unit=model.units.summarise_units(self._model.get_free_variable_symbol())```

would be a nice addition if the one that converts the model could take a unit definition so I don't have to first add it to the model.

**Comment by jonc125** [comment]
I think if you're adding new variables the `order_added` would keep incrementing? This may in part be why pycml uses `display_name` for sorting particularly in Web Lab use cases!

I agree with the suggestion for using a `pint` units definition when asking for conversion factors, rather than having to register one with the `UnitsStore`. That seems like quite a long-winded way to get the units for a variable too; passing the `units` field from the associated `MetaDummy` might be better? And perhaps a helper method `Model.get_units_for(symbol)` which does this?

**Comment by MauriceHendrix** [comment]
sounds good

yes you are right `order_added` would keep increasing. A sort of display_name sorting might be fine especially if that's what pycml does. It sould also be possible to go for float numbers plenty of room between 2 whole numbers to make lots of additional variables :) )

**Comment by MauriceHendrix** [comment]
By the way the way the code for chaste codegen does it at the moment is without replacing variables.
say V is in Volt then:
- I find V and multiply by conversion factor
- use subs on other equations to substitute vs for 1/factor * V

It's probably less easy/safe but it does get round any issues with ordering of the variables

**Comment by MichaelClerx** [comment]
## Literal constant, with API calls
From
```
x = 1 [pA]
  in [pA]
  oxmeta: current
y = 1 / x
  in [1/pA]
```
To
```
input_current = 1e-3 [nA]
  in [nA]
  oxmeta: current
x = input_current * 1e3 [pA/nA]
  in [pA]
y = 1 / x
  in [1/pA]
```
In code:
```
# Get the x variable and its equation
x_symbol = model.get_symbol_by_ontology_term(oxmeta, 'current')
x_eq = model.get_equation(x_symbol)
x_lhs = x_eq.lhs
x_unit = model.get_meta_dummy(x_symbol).units

# Create the new variable
input_unit = somehow get desired unit object
input_name = somehow get name "input_current" without name clashes
input_lhs = model.add_variable(name=input_name, units=input_unit)
input_rhs = somehow convert x_eq to the new units, using pint directly? or via the unitstore?
model.set_equation(input_lhs, input_rhs)

# Update the equation for x
conversion_factor = get conversion factor, same question as above
model.set_equation(x_lhs, input_lhs * conversion_factor)

# Update the annotations
somehow remove annotation from x
somehow add annotation for input_rhs
```

Comments / suggestions? @jonc125 @MauriceHendrix @skeating ?

**Comment by MichaelClerx** [comment]
> yes you are right order_added would keep increasing. A sort of display_name sorting might be fine especially if that's what pycml does. It would also be possible to go for float numbers plenty of room between 2 whole numbers to make lots of additional variables :) )

I think that's a very good idea, as the ordering of the variables can change with manipulations etc., so we probably shouldn't even be thinking about that kind of thing when we're working out what to do here :D

**Comment by jonc125** [comment]
Updating the annotations just requires moving the cmeta:id attribute from the original to new variable - no change to the RDF needed. (Or in cellmlmanip, set the cmeta_id properties on the associated `MetaDummy`s.)

**Comment by MichaelClerx** [comment]
Thanks! Have updated accordingly

**Comment by skeating** [comment]
What are the priorities for adding unit conversion functionality to cellmlmanip.

**Comment by MauriceHendrix** [comment]
> What are the priorities for adding unit conversion functionality to cellmlmanip.

In what sense priorities?
in general I was hoping for a method that takes a variable and units and adjusts the model. In my case I'm converting some state_vars, but also a few others like membrane_capacitance and membrane_stimulus_current.

**Comment by mirams** [comment]
you mean a list of sub tasks/tickets @skeating ? If it isn't clear how to prioritise tasks I'd start test-driven with some of the existing protocols and see what they need to be able to do to run all the models on WL1.

**Comment by mirams** [comment]
(the `SteadyState1Hz.txt` should do almost everything Maurice is trying to do in WebLab).

**Comment by jonc125** [comment]
Yes, we should drive this by use cases, but I think we're currently on the first of these, namely the `GraphState` protocol used with models that require units conversions (for time and voltage). Earlier comments set out some principles and examples. Based on what protocols need (and what pycml also does for the Chaste interface), we want methods on `Model` to:
1. Mark a variable as an input in given units, adding conversion equations if needed
2. Mark a variable as an output in given units, adding conversion equations if needed

Exactly what these do depends on whether the variable in question is categorised as state/free/parameter/computed. Michael gave [examples for treating inputs above](https://github.com/ModellingWebLab/cellmlmanip/issues/77#issuecomment-554311618). Note that you can't make a computed variable an input! Also note that when converting time you need to modify *every* ODE.

Outputs are easier as they don't vary by type - you just need to add a new variable that's set from the existing variable, and move the `cmeta:id`. The one case to watch out for is trying to add the same variable as both an input and an output but in different units, because the `cmeta:id` can't go on two variables! But catching that error is probably better done by weblab-fc rather than cellmlmanip.

For both methods, it might be nice if they're clever enough to modify the graph(s) themselves rather than just invalidating the graph and letting it be re-calculated later. But that can happen in a second PR!

**Comment by skeating** [comment]
So a function:
Model.convert_units('sv1', 'volt')

on my basic ode

    <component name="env_ode">
        
        <variable name="time" public_interface="in" units="ms"/>
        <variable cmeta:id="sv11" initial_value="2" name="sv1" units="mV"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
                <eq/>
                <apply>
                    <diff/>
                    <bvar>
                        <ci>time</ci>
                    </bvar>
                    <ci>sv1</ci>
                </apply>
                <cn cellml:units="mV_per_ms">1</cn>
            </apply>
        </math>
    </component>

which would return a model with

    <component name="env_ode">
        
        <variable name="time" public_interface="in" units="ms"/>
        <variable cmeta:id="sv11" initial_value="0.002" name="sv1" units="V"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
                <eq/>
                <apply>
                    <diff/>
                    <bvar>
                        <ci>time</ci>
                    </bvar>
                    <ci>sv1</ci>
                </apply>
                <cn cellml:units="V_per_ms">0.001</cn>
            </apply>
        </math>
    </component>
 

??

**Comment by jonc125** [comment]
No, you want to keep the existing variables & equations, and add new ones if a conversion is needed. I'd also use methods `add_input` and `add_output` or similar, not just one `convert_units`, because the behaviour does vary between them.

The methods would take a `VariableDummy` and `Unit` object as arguments (though possibly accept names too?).

In your example, `add_input(sv1, volt)` would give (not in MathML, because it only changes the internal `Model` equations and variables)
- Variables:
    - `time` in `ms`
    - `sv1` in `mV`
    - `sv1_converted` in `V`, initial `0.002`, id `sv11`
    - `original_rhs` in `mV_per_ms`
- Equations:
    - `original_rhs = 1 mV_per_ms`
    - `Derivative(sv1_converted, time) = original_rhs * 0.001`
    - `sv1 = sv1_converted * 1000`

And if `Derivative(sv1, time)` appears on the RHS of any equation, it needs to be replaced by `original_rhs`.

Of course, any new variable names need to be unique within the model. So `original_rhs` is probably not the best choice! Perhaps `d_sv1_d_time` or similar as a first attempt, and append `_1` etc if that already exists?

**Comment by MauriceHendrix** [comment]
Hhmm how are input/ output different and would it not be possible for cellmlmanip to work out if it's input/output?

**Comment by skeating** [comment]
Thanks @jonc125 that makes it clearer

**Comment by jonc125** [comment]
> Hhmm how are input/ output different and would it not be possible for cellmlmanip to work out if it's input/output?

No, because it's the external context that determines this, you can't deduce it from the model. It depends on whether the outside world wants to read (output) or write (input) the variable (or both - in which case use input).

**Comment by MauriceHendrix** [comment]
> > Hhmm how are input/ output different and would it not be possible for cellmlmanip to work out if it's input/output?
> 
> No, because it's the external context that determines this, you can't deduce it from the model. It depends on whether the outside world wants to read (output) or write (input) the variable (or both - in which case use input).

In that case would it make sense to have 1 method with a flag? Because using input to mean both is kinda confusing. (I get that 'both' is just a consequence of converting input but you shouldn't have to know that)

**Comment by jonc125** [comment]
> In that case would it make sense to have 1 method with a flag? Because using input to mean both is kinda confusing. (I get that 'both' is just a consequence of converting input but you shouldn't have to know that)

The code for handling input or output is quite different though, so you'd end up having 2 methods internally. Also from a Web Lab perspective the protocol talks about both inputs & outputs, so it's a natural match to have the methods called that. You can (and Web Lab does) call `add_input` and `add_output` for the same variable, which is fine provided you convert to the same units in both calls, and the input case is called first; the implementation can check this and give a sensible error if not. If you know how they're implemented, and you're calling manually, you can just get away with omitting the `add_output` call when doing both because it's a no-op. So that's what pycml does for Chaste code gen.

> Am I missing somethng? If in the equation the lhs is unique (which it should be) then something like
> `var_original_rhs` where `var` is the name of the lhs should be unique too right?

That's true, it probably would be. It was much trickier in pycml because you still had components, and so had to create variables with essentially the same name in different components, connecting them together, so clashes were common in intermediate components.

> Unless of course the same variable gets converted multiple times.

I don't think you would for Chaste or Web Lab. But other users of cellmlmanip might want to output the same variable in two different units? Probably not worth worrying about before it happens though!

**Comment by MauriceHendrix** [comment]
> > Unless of course the same variable gets converted multiple times.
> 
> I don't think you would for Chaste or Web Lab. But other users of cellmlmanip might want to output the same variable in two different units? Probably not worth worrying about before it happens though!
sure but in that case names may not automatically be unique 

In terms of the naming `add_input` and `add_output` to convert units just sounds like you're using a method's side effect that is intended to do something else. I remember being pretty surprised in PyCml about that too.

**Comment by jonc125** [comment]
But how you do the conversion depends on which way you want the information to flow, so it's not a side effect, it's essential.

**Comment by skeating** [comment]
@jonc125 Could you outline how an add_output function would be different, please :-)

**Comment by jonc125** [comment]
The examples above were inputs, and vary depending on the type of variable. For outputs it's the same whatever the type.

If your original model is say
```
my_variable [mV] = some_equation
    RDF oxmeta:super_v
```
and you want `add_output(my_variable, volts)`, then you get
```
my_variable_converted [V] = my_variable * 0.001
    RDF oxmeta:super_v
my_variable [mV] = some_equation
```

I guess a generic `convert_variable(var, units)` method might do the same as this but without moving the annotation? Though not sure if that would be useful for @MauriceHendrix; I think both the Chaste interface & Web Lab always want to move the annotation. It was only internal stuff in pycml due to multiple components that didn't iirc.
